### ISSUE TITLE
Not printing?

### ISSUE THREAD

**Issue by cacocalo** [sabat54i/photoboothdiy#3]
Hi all,
I have everything working, but the print no longer works. At first- it would print the first time I press the button and the next time it would do everything but print. Now it never print. It always saves the images created.

I'm using a Canon Selphy CP1300 and the Canon SELPHY CP900 - CUPS+Gutenprint v5.2.11 CUPS driver.

When I escape out of the script, this is the error message I get:

False
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "camera.py", line 454, in main
WaitForEvent()
File "camera.py", line 441, in WaitForEvent
for event in pygame.event.get():
error: video system not initialized

Anyone have any ideas? Thanks so much in advance!!

Jennifer

    Thank

**Comment by TheJerem76** [comment]
Hello,

Is this printer well configured ?

Check https://github.com/sabat54i/photoboothdiy/issues/5 to test the config.

On my side I use another printer working with wifi, and that's OK.

When the printer is off, the behaviour I see is the one you describe.
